name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build win-x64
      run: dotnet build -r win-x64 CBRE.Editor
    - name: Build linux-x64
      run: dotnet build -r linux-x64 CBRE.Editor
    - uses: actions/upload-artifact@v2
      with:
        name: CBRE.Editor win-x64 Build
        path: CBRE.Editor/bin/Debug/net5.0/win-x64/
        retention-days: 5
    - uses: actions/upload-artifact@v2
      with:
        name: CBRE.Editor linux-x64 Build
        path: CBRE.Editor/bin/Debug/net5.0/linux-x64/
        retention-days: 5
